- name: install workstation repos
  dnf:
    name: fedora-workstation-repositories

- name: install chrome
  dnf:
    name: google-chrome-stable
    enablerepo: google-chrome
  when:
  - ansible_architecture != 'aarch64'

- name: settle for chromium
  dnf:
    name: chromium
  when:
  - ansible_architecture == 'aarch64'
