---
- name: Install flatpak
  ansible.builtin.dnf:
    name: flatpak

- name: Install flatpak repo
  community.general.flatpak_remote:
    name: flathub
    method: system
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
