- name: Create install directory for hack
  ansible.builtin.file:
    path: /usr/share/fonts/hack
    state: directory

# https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip
- name: Install hack
  ansible.builtin.copy:
    src: ttf/{{ item }}
    dest: /usr/share/fonts/hack/{{ item }}
  loop:
  - Hack-Bold.ttf
  - Hack-BoldItalic.ttf
  - Hack-Italic.ttf
  - Hack-Regular.ttf
  register: new_fonts

- name: Update the font cache
  ansible.builtin.command: fc-cache -v
  changed_when: true
  when:
  - new_fonts.changed
