- name: install git and friends
  pacman:
    name:
    - gist
    - git
    - hub
  when: ansible_distribution == 'Archlinux'

- name: configure git, gist
  template:
    src: "home/{{ item }}"
    dest: "/home/dolph/.{{ item }}"
    owner: dolph
    group: dolph
  with_items:
  - gitconfig
  - gitignore_global
  - gist
