- name: install go
  pacman:
    name: go
  when: ansible_distribution == 'Archlinux'

- name: create GOPATH
  file:
    path: /home/dolph/go
    state: directory
    owner: dolph
    group: dolph

- name: install vim-go plugins
  become: true
  become_user: dolph
  command: vim +GoInstallBinaries! +qall
