- name: set system font size
  set_fact:
    font_size: 12

- name: install i3
  dnf:
    name:
    - i3
    - maim
    - numix-gtk-theme
    - rofi
    - lxappearance

- name: create i3 config dirs
  file:
    dest: /home/{{ whoami }}/.config/{{ dir }}
    state: directory
    owner: "{{ whoami}}"
    group: "{{ whoami}}"
  loop:
  - i3
  - i3status
  loop_control:
    loop_var: dir

- name: configure i3
  template:
    src: home/config/{{ dir }}/config
    dest: /home/{{ whoami }}/.config/{{ dir }}/config
    owner: "{{ whoami}}"
    group: "{{ whoami}}"
  loop:
  - i3
  - i3status
  loop_control:
    loop_var: dir
  notify: restart i3

- name: configure urvxt
  template:
    src: home/Xresources
    dest: /home/{{ whoami }}/.Xresources
    owner: "{{ whoami}}"
    group: "{{ whoami}}"
  notify: reload X database

# https://cravencode.com/post/essentials/enable-tap-to-click-in-i3wm/
- name: configure touchpad tap-to-click
  template:
    src: etc/X11/xorg.conf.d/90-touchpad.conf
    dest: /etc/X11/xorg.conf.d/90-touchpad.conf

- name: configure X
  template:
    src: home/xinitrc
    dest: /home/{{ whoami }}/.xinitrc
    owner: "{{ whoami}}"
    group: "{{ whoami}}"
    mode: 0770
