- name: install i3
  dnf:
    name:
    - i3
    - numix-gtk-theme
    - rofi
    - lxappearance

- name: create i3 config dir
  file:
    dest: /home/{{ whoami }}/.config/i3
    state: directory
    owner: "{{ whoami}}"
    group: "{{ whoami}}"

- name: configure i3
  template:
    src: home/config/i3/config
    dest: /home/{{ whoami }}/.config/i3/config
    owner: "{{ whoami}}"
    group: "{{ whoami}}"

- name: configure urvxt
  template:
    src: home/Xresources
    dest: /home/{{ whoami }}/.Xresources
    owner: "{{ whoami}}"
    group: "{{ whoami}}"

# https://cravencode.com/post/essentials/enable-tap-to-click-in-i3wm/
- name: configure touchpad tap-to-click
  template:
    src: etc/X11/xorg.conf.d/90-touchpad.conf
    dest: /etc/X11/xorg.conf.d/90-touchpad.conf
