- name: install i3
  dnf:
    name:
    - i3
    - numix-gtk-theme
    - rofi
    - lxappearance

# ~/.config/i3/config

- name: configure urvxt
  template:
    src: home/Xresources
    dest: /home/{{ whoami }}/.Xresources
    owner: "{{ whoami}}"
    group: "{{ whoami}}"

# https://cravencode.com/post/essentials/enable-tap-to-click-in-i3wm/
