- name: get horizontal screen size
  shell: xrandr | grep '*' | awk '{print $1}' | head -1 | cut -d'x' -f1
  check_mode: false
  register: horizontal_resolution
  changed_when: false

- name: get vertical screen size
  shell: xrandr | grep '*' | awk '{print $1}' | head -1 | cut -d'x' -f2
  check_mode: false
  register: vertical_resolution
  changed_when: false

- name: set system font size
  set_fact:
    font_size: "{{ (13 + (horizontal_resolution.stdout | int * vertical_resolution.stdout | int) / (2 * 1920 * 1080)) | int }}"

- name: report detected resolution
  debug:
    msg: "resolution={{ horizontal_resolution.stdout }}x{{ vertical_resolution.stdout }} font_size={{ font_size }}"
  changed_when: true

- name: install i3 and friends
  dnf:
    name:
    - alacritty
    - bluez
    - dunst
    - i3
    - lxappearance
    - maim
    - numix-gtk-theme
    - rofi
    - unclutter-xfixes
    - xclip
    - xdotool
    - xset
    - xsetroot
    - xss-lock

- name: Install i3-instant-layout from pypi
  become: true
  become_user: "{{ whoami }}"
  pip:
    name: i3-instant-layout
    state: latest

- name: install screensaver required by IBM
  dnf:
    name: xscreensaver
  when: ibm_managed

- name: Check for Bluetooth device
  ansible.builtin.shell: "bluetoothctl list | grep -oE '([[:xdigit:]]{2}:){5}[[:xdigit:]]{2}'"
  register: bluetooth_devices
  ignore_errors: true
  changed_when: false

- name: Register bluetooth support
  set_fact:
    bluetooth_support: "{{ (bluetooth_devices.stdout != '') | bool }}"

- name: create i3 config dirs
  file:
    dest: /home/{{ whoami }}/.config/{{ dir }}
    state: directory
    owner: "{{ whoami}}"
    group: "{{ whoami}}"
  loop:
  - dunst
  - i3
  - i3status
  - rofi
  loop_control:
    loop_var: dir

- name: configure i3
  template:
    src: home/config/{{ dir }}/config
    dest: /home/{{ whoami }}/.config/{{ dir }}/config
    owner: "{{ whoami}}"
    group: "{{ whoami}}"
  loop:
  - i3
  - i3status
  loop_control:
    loop_var: dir
  notify: restart i3

- name: configure rofi/dmenu
  template:
    src: home/config/rofi/config.rasi
    dest: /home/{{ whoami }}/.config/rofi/config.rasi
    owner: "{{ whoami}}"
    group: "{{ whoami}}"
  notify: restart i3

- name: configure alacritty
  template:
    src: home/alacritty.toml
    dest: /home/{{ whoami }}/.alacritty.toml
    owner: "{{ whoami}}"
    group: "{{ whoami}}"

# https://cravencode.com/post/essentials/enable-tap-to-click-in-i3wm/
- name: configure touchpad tap-to-click
  template:
    src: etc/X11/xorg.conf.d/90-touchpad.conf
    dest: /etc/X11/xorg.conf.d/90-touchpad.conf

- name: disable mouse acceleration
  template:
    src: etc/X11/xorg.conf.d/50-mouse-acceleration.conf
    dest: /etc/X11/xorg.conf.d/50-mouse-acceleration.conf

- name: configure X
  template:
    src: home/xinitrc
    dest: /home/{{ whoami }}/.xinitrc
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: 0770

- name: install xrandr & autorandr
  dnf:
    name:
    - autorandr
    - xrandr

- name: enable autorandr
  systemd:
    name: autorandr
    enabled: true

- name: set greeter background
  ini_file:
    path: /etc/lightdm/lightdm-gtk-greeter.conf
    section: greeter
    option: background
    value: "#000000"
    no_extra_spaces: true

- name: configure dunst
  template:
    src: home/config/dunst/dunstrc
    dest: /home/{{ whoami }}/.config/dunst/dunstrc
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: 0660
