- name: Get current localectl status
  ansible.builtin.command:
    argv:
      - localectl
      - status
  register: localectl_status
  changed_when: false

- name: Set Caps Lock to Escape in X11 keymap
  ansible.builtin.command:
    argv:
      - localectl
      - set-x11-keymap
      - us
      - ""
      - ""
      - caps:escape
  become: true
  changed_when: true
  when: "'X11 Options: caps:escape' not in localectl_status.stdout"
