---
- name: Check if this is an IBM-managed system
  ansible.builtin.stat:
    path: /opt/ibm/
  register: ibm
  tags: always

- name: Set fact
  ansible.builtin.set_fact:
    ibm_managed: "{{ ibm.stat.isdir is defined | bool }}"
  tags: always

- name: Set timezone
  community.general.timezone:
    name: America/Chicago
  tags: timezone

- name: Remap keyboard
  ansible.builtin.import_tasks: keyboard.yml
  tags: keyboard

- name: Removed unused desktop packages
  ansible.builtin.dnf:
    name:
    - asunder
    - claws-mail
    - geany
    - pidgin
    - pragha
    state: absent
  tags: dnf

- name: Configure custom fonts
  ansible.builtin.import_tasks: fonts.yml
  tags: fonts

- name: Configure terminal
  ansible.builtin.import_tasks: terminal.yml
  tags:
  - terminal

- name: Install rpmfusion
  ansible.builtin.import_tasks: rpmfusion.yml
  tags: rpmfusion

- name: Configure vlc
  ansible.builtin.import_tasks: vlc.yml
  tags: vlc

- name: Configure i3
  ansible.builtin.import_tasks: i3.yml
  tags: i3

- name: Install google chrome
  ansible.builtin.import_tasks: chrome.yml
  tags: chrome

- name: Install nvidia drivers
  ansible.builtin.import_tasks: nvidia.yml
  tags: nvidia

- name: Configure pulseaudio
  ansible.builtin.import_tasks: pulseaudio.yml
  tags: pulseaudio

- name: Configure signal
  ansible.builtin.import_tasks: signal.yml
  tags: signal

- name: Configure gimp
  ansible.builtin.import_tasks: gimp.yml
  tags: gimp

- name: Install Brother printer dependencies
  ansible.builtin.dnf:
    name: perl-File-Copy
  tags: brother
