---
- name: install additional packages on arch
  pacman:
    name:
    - vlc
  when: ansible_distribution == 'Archlinux'

- name: install additional packages on ubuntu
  apt:
    name:
    - vlc
  when: ansible_distribution == 'Ubuntu'

- name: configure xfce
  include: xfce.yml
  tags: xfce

- name: configure custom fonts
  include: fonts.yml
  tags: fonts

- name: install google chrome
  include: chrome.yml
  tags: chrome

# TODO: terminal config
