- name: set timezone
  timezone:
    name: America/Chicago
  tags: timezone

- name: disable dnfdragora-updater
  include: dnfdragora.yml
  tags:
  - dnf
  - dnfdragora

- name: configure custom fonts
  include: fonts.yml
  tags: fonts

- name: configure terminal
  include: terminal.yml
  tags:
  - terminal
  - xfce

- name: install rpmfusion
  include: rpmfusion.yml
  tags: rpmfusion

- name: configure vlc
  include: vlc.yml
  tags: vlc

- name: configure xfce
  include: xfce.yml
  tags: xfce

- name: install google chrome
  include: chrome.yml
  tags: chrome

- name: install nvidia drivers
  include: nvidia.yml
  tags: nvidia

- name: install virtualbox
  include: virtualbox.yml
  tags: virtualbox

- name: configure vagrant
  include: vagrant.yml
  tags: vagrant

- name: configure pulseaudio
  include: pulseaudio.yml
  tags: pulseaudio
