---
- name: set timezone
  timezone:
    name: America/Chicago
  tags: timezone

- name: configure terminal
  include: terminal.yml
  tags:
  - terminal
  - xfce

- name: configure vlc
  include: vlc.yml
  tags: vlc

- name: configure xfce
  include: xfce.yml
  tags: xfce

- name: configure custom fonts
  include: fonts.yml
  tags: fonts

- name: install google chrome
  include: chrome.yml
  tags: chrome
