# https://askubuntu.com/a/765024/22414
- name: add echo cancellation to mic input
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: '^load-module module-echo-cancel'
    line: load-module module-echo-cancel aec_method=webrtc aec_args="analog_gain_control=0 digital_gain_control=1"
  notify: restart pulseaudio
