- name: switch back to pulseaudio from pipewire
  command:
    cmd: dnf swap -y --allowerasing pipewire-pulseaudio pulseaudio
    warn: false # dnf module does not support swap operation
  register: dnf_swap
  changed_when: "'Nothing to do.' not in dnf_swap.stdout"

# https://askubuntu.com/a/765024/22414
- name: add echo cancellation to mic input
  blockinfile:
    path: /etc/pulse/default.pa
    marker: '# {mark} MICROPHONE ECHO CANCELLATION BLOCK'
    block: |
      load-module module-echo-cancel use_master_format=1 aec_method=webrtc aec_args="analog_gain_control=0\ digital_gain_control=1" source_name=echoCancel_source sink_name=echoCancel_sink
      set-default-source echoCancel_source
      set-default-sink echoCancel_sink
    create: false # This file should already exist if we're not on pipewire
  notify: restart pulseaudio
