- name: ensure we're pulseaudio is gone
  dnf:
    name: pulseaudio
    state: absent

- name: ensure pipewire is running
  dnf:
    name: pipewire-pulseaudio

# https://askubuntu.com/a/765024/22414
- name: add echo cancellation to mic input
  blockinfile:
    path: /etc/pulse/default.pa
    marker: '# {mark} MICROPHONE ECHO CANCELLATION BLOCK'
    block: |
      load-module module-echo-cancel use_master_format=1 aec_method=webrtc aec_args="analog_gain_control=0\ digital_gain_control=1" source_name=echoCancel_source sink_name=echoCancel_sink
      set-default-source echoCancel_source
      set-default-sink echoCancel_sink
    create: false # This file should already exist if we're not on pipewire
  when: false # FIXME: replace this task for pipewire
  notify: restart pulseaudio
