# https://askubuntu.com/a/765024/22414
- name: add echo cancellation to mic input
  blockinfile:
    path: /etc/pulse/default.pa
    marker: '# {mark} MICROPHONE ECHO CANCELLATION BLOCK'
    block: |
      load-module module-echo-cancel use_master_format=1 aec_method=webrtc aec_args="analog_gain_control=0\ digital_gain_control=1" source_name=echoCancel_source sink_name=echoCancel_sink
      set-default-source echoCancel_source
      set-default-sink echoCancel_sink
  notify: restart pulseaudio
