# This is required for Chrome, VLC, and Nvidia drivers
- name: install rpmfusion
  dnf:
    name:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    disable_gpg_check: true  # Trust HTTPS, and let the rpmfusion packages install GPG keys.
