- name: Disable terminal bell on boot by disabling PC speaker
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/nobeep.conf
    create: true
    line: blacklist pcspkr
    owner: root
    group: root
    mode: 0644

- name: Disable terminal bell immediately
  community.general.modprobe:
    name: pcspkr
    state: absent
