- name: create xfce terminal config dir
  file:
    dest: "/home/{{ whoami }}/.config/xfce4/terminal/"
    state: directory
    owner: "{{ whoami }}"
    group: "{{ whoami }}"

- name: push terminal config
  template:
    src: home/config/xfce4/terminal/terminalrc
    dest: "/home/{{ whoami }}/.config/xfce4/terminal/terminalrc"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
