- name: install tmux
  pacman:
    name: tmux
  when: ansible_distribution == 'Archlinux'

- name: configure tmux
  template:
    src: home/tmux.conf
    dest: /home/dolph/.tmux.conf
    owner: dolph
    group: dolph
