---
- name: install vlc
  dnf:
    name:
    - vlc
    - vlc-extras

- name: allow VLC to serve Chromecast streams
  ansible.posix.firewalld:
    port: "{{ port }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
  - 8009/tcp
  - 8010/tcp
  loop_control:
    loop_var: port
