- name: configure xmodmap
  template:
    src: home/Xmodmap
    dest: "/home/{{ whoami }}/.Xmodmap"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  register: xmodmap

- name: apply xmodmap
  become: true
  become_user: "{{ whoami }}"
  shell: if [ -n "${DISPLAY+x}" ]; then xmodmap ~/.Xmodmap; fi
  when: xmodmap.changed
