- name: remove old xmodmap config to remap caps lock
  file:
    path: "/home/{{ whoami }}/.Xmodmap"
    state: absent

- name: load panel from backup
  block:
  - name: move panel backup into position
    become: true
    become_user: "{{ whoami }}"
    copy:
      src: panel-backup.tar.gz
      decrypt: true
      dest: /tmp/panel-backup.tar.gz
    tags:
    - panel
    - never

  - name: load xfce panel backup
    become: true
    become_user: "{{ whoami }}"
    command: xfce4-panel-profiles load /tmp/panel-backup.tar.gz
    tags:
    - panel
    - never

  always:
  - name: cleanup decrypted panel backup
    file:
      path: /tmp/panel-backup.tar.gz
      state: absent
    tags:
    - panel
    - never

- name: install dependencies to manage xml
  dnf:
    name: python3-lxml

- name: check for whiskermenu shortcuts
  become: true
  become_user: "{{ whoami }}"
  xml:
    path: "/home/{{ whoami }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    xpath: /channel[@name="xfce4-keyboard-shortcuts"]/property[@name="commands"][@type="empty"]/property[@name="custom"][@type="empty"]/property[@value="xfce4-popup-whiskermenu"]
    count: true
  register: whiskermenu_shortcuts

- name: make the Windows key open the whiskermenu
  become: true
  become_user: "{{ whoami }}"
  xml:
    path: "/home/{{ whoami }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    xpath: /channel[@name="xfce4-keyboard-shortcuts"]/property[@name="commands"][@type="empty"]/property[@name="custom"][@type="empty"]
    add_children:
    - property:
        name: Super_L
        type: string
        value: xfce4-popup-whiskermenu
  when: whiskermenu_shortcuts.count == 0
