- name: configure xmodmap
  template:
    src: home/Xmodmap
    dest: /home/dolph/.Xmodmap
    owner: dolph
    group: dolph
  register: xmodmap

- name: apply xmodmap
  become: true
  become_user: dolph
  command: xmodmap ~/.Xmodmap
  when: xmodmap.changed

