- name: configure xmodmap
  template:
    src: home/Xmodmap
    dest: "/home/{{ whoami }}/.Xmodmap"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  register: xmodmap

- name: apply xmodmap
  become: true
  become_user: "{{ whoami }}"
  command: xmodmap ~/.Xmodmap
  when: xmodmap.changed
