- name: Install chromedriver
  ansible.builtin.dnf:
    name:
    - chromedriver
    - chromium

- name: Enable SSH forwarding for sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults env_keep += "SSH_AUTH_SOCK"'

- name: Get value of SSH_AUTH_SOCK
  ansible.builtin.command: echo $SSH_AUTH_SOCK
  changed_when: false
  register: ssh_auth_sock

- name: Let whoami read the SSH agent remote socket dir
  ansible.posix.acl:
    path: "{{ ssh_auth_sock.stdout | dirname }}"
    entity: "{{ whoami }}"
    etype: user
    permissions: x
    state: present

- name: Let whoami use the SSH agent remote socket
  ansible.posix.acl:
    path: "{{ ssh_auth_sock.stdout }}"
    entity: "{{ whoami }}"
    etype: user
    permissions: rwx
    state: present

- name: Clone movie poster kiosk  # noqa: latest[git]
  become: true
  become_user: "{{ whoami }}"
  become_method: sudo
  become_flags: -E
  ansible.builtin.git:
    repo: git@github.com:dolph/movie-poster-kiosk.git
    dest: "/home/{{ whoami }}/dolph/movie-poster-kiosk"
    update: true

- name: Install requirements
  become: true
  become_user: "{{ whoami }}"
  become_method: sudo
  become_flags: -E
  ansible.builtin.pip:
    executable: /usr/bin/pip
    requirements: "/home/{{ whoami }}/dolph/movie-poster-kiosk/requirements.txt"
    virtualenv: "/home/{{ whoami }}/venv/movie-poster-kiosk"
    state: latest

- name: Create systemd user directory
  ansible.builtin.file:
    path: /home/{{ whoami }}/.config/systemd/user/
    state: directory
    owner: "{{ whoami }}"
    group: "{{ whoami }}"

- name: Install systemd user units
  ansible.builtin.template:
    src: home/config/systemd/user/{{ unit }}
    dest: /home/{{ whoami }}/.config/systemd/user/{{ unit }}
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  loop:
  - kiosk-web.service
  - kiosk-crawler.service
  - kiosk-crawler.timer
  loop_control:
    loop_var: unit
  notify: Reload systemd

- name: Enable systemd user units
  become: true
  become_user: "{{ whoami }}"
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: true
    scope: user
  loop:
  - kiosk-web.service
  - kiosk-crawler.service
  - kiosk-crawler.timer
  loop_control:
    loop_var: unit

- name: Start simple systemd service units
  become: true
  become_user: "{{ whoami }}"
  ansible.builtin.systemd:
    name: "{{ unit }}"
    state: started
    scope: user
  loop:
  - kiosk-web.service
  - kiosk-crawler.timer
  loop_control:
    loop_var: unit
