- name: set timezone
  timezone:
    name: America/Chicago
  tags: timezone

- name: remove screensavers
  dnf:
    name: xscreensaver*
    state: absent

- name: install package dependencies
  dnf:
    name:
    - firefox

- name: automatically login as personal user
  ini_file:
    path: /etc/lightdm/lightdm.conf
    section: LightDM
    option: autologin-user
    value: "{{ whoami }}"

- name: automatically login immediately
  ini_file:
    path: /etc/lightdm/lightdm.conf
    section: LightDM
    option: autologin-user-timeout
    value: 0

- name: launch Firefox in kiosk mode automatically
  become: true
  become_user: "{{ whoami}}"
  ini_file:
    path: /home/{{ whoami }}/.config/autostart/firefox.desktop
    section: Desktop Entry
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_dict:
    Name: Firefox
    Exec: /usr/bin/firefox --kiosk https://play.google.com/store/movies
    Comment: Launch Firefox in kiosk mode
    Terminal: false
    Type: Application
    StartupNotify: false
    Icon: firefox

- name: hide the mouse when idle
  include: unclutter.yml
  tags: unclutter

- name: disable display power management on boot
  become: true
  become_user: "{{ whoami}}"
  ini_file:
    path: /home/{{ whoami }}/.config/autostart/power-manager.desktop
    section: Desktop Entry
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_dict:
    Name: Power Manager
    Exec: xfce4-power-manager -q
    Comment: Disable power manager
    Terminal: false
    Type: Application
    StartupNotify: false

- name: disable display power management immediately
  become: true
  become_user: "{{ whoami }}"
  command: xfce4-power-manager -q
