- name: set timezone
  timezone:
    name: America/Chicago
  tags: timezone

- name: install xfce
  dnf:
    name: '@Xfce Desktop'
  tags: xfce

- name: boot into graphical desktop
  file:
    src: /lib/systemd/system/runlevel5.target
    path: /etc/systemd/system/default.target
    state: link
  tags: xfce

- name: automatically login on boot
  include: autologin.yml
  tags: autologin

- name: configure chromium
  include: chromium.yml
  tags: chromium

- name: hide the mouse when idle
  include: unclutter.yml
  tags: unclutter

- name: disable dnfdragora notifications
  include: dnfdragora.yml
  tags: dnfdragora

- name: keep the display on permanently
  include: stay-on.yml
  tags: stay-on
