---
- name: Set timezone
  community.general.timezone:
    name: America/Chicago
  tags: timezone

- name: Install xfce
  ansible.builtin.dnf:
    name: "@Xfce Desktop"
  tags: xfce

- name: Boot into graphical desktop
  ansible.builtin.file:
    src: /lib/systemd/system/runlevel5.target
    path: /etc/systemd/system/default.target
    state: link
  tags: xfce

- name: Automatically login on boot
  ansible.builtin.import_tasks: autologin.yml
  tags: autologin

- name: Configure web browser
  ansible.builtin.import_tasks: browser.yml
  tags: browser

- name: Hide the mouse when idle
  ansible.builtin.import_tasks: unclutter.yml
  tags: unclutter

- name: Disable dnfdragora notifications
  ansible.builtin.import_tasks: dnfdragora.yml
  tags: dnfdragora

- name: Keep the display on permanently
  ansible.builtin.import_tasks: stay-on.yml
  tags: stay-on

- name: Configure autopilot
  ansible.builtin.import_tasks: autopilot.yml
  tags: autopilot
