- name: set timezone
  timezone:
    name: America/Chicago
  tags: timezone

- name: automatically login on boot
  include: autologin.yml
  tags: autologin

- name: configure firefox
  include: firefox.yml
  tags: firefox

- name: hide the mouse when idle
  include: unclutter.yml
  tags: unclutter

- name: disable dnfdragora notifications
  include: dnfdragora.yml
  tags: dnfdragora

- name: keep the display on permanently
  include: stay-on.yml
  tags: stay-on
