- name: remove screensavers
  dnf:
    name: xscreensaver*
    state: absent

- name: disable display power management on boot
  become: true
  become_user: "{{ whoami}}"
  ini_file:
    path: /home/{{ whoami }}/.config/autostart/power-manager.desktop
    section: Desktop Entry
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_dict:
    Name: Power Manager
    Exec: sh -c "sleep 60; xfce4-power-manager -q"
    Comment: Disable power manager
    Terminal: false
    Type: Application
    StartupNotify: false

- name: disable display power management immediately
  become: true
  become_user: "{{ whoami }}"
  command: xfce4-power-manager -q
  async: 60
  poll: 0

- name: disable energy star on boot
  become: true
  become_user: "{{ whoami }}"
  ini_file:
    path: /home/{{ whoami }}/.config/autostart/energy-star.desktop
    section: Desktop Entry
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_dict:
    Name: Disable Energy Star
    Exec: sh -c "sleep 60; xset -dpms"
    Comment: Disable energy star power management for display
    Terminal: false
    Type: Application
    StartupNotify: false

- name: disable energy star immediately
  become: true
  become_user: "{{ whoami }}"
  environment:
    DISPLAY: ":0.0"
  command: xset -dpms
  async: 60
  poll: 0
