---
- name: Install dnf-automatic
  ansible.builtin.dnf:
    name: dnf-automatic
  register: headless_task
  until: headless_task is succeeded
  retries: 20
  delay: 0

- name: Configure dnf-automatic
  ansible.builtin.template:
    src: etc/dnf/automatic.conf
    dest: /etc/dnf/automatic.conf
    mode: "0644"
    owner: root
    group: root

- name: Ensure dnf-automatic is running
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true

- name: Schedule automatic reboots when necessary
  ansible.builtin.template:
    src: etc/systemd/system/{{ unit }}
    dest: /etc/systemd/system/{{ unit }}
    mode: "0644"
  loop:
    - reboot.service
    - reboot.timer
  loop_control:
    loop_var: unit
  register: headless_reboot_units

- name: Enable scheduled reboots
  ansible.builtin.systemd:
    name: reboot.timer
    state: started
    enabled: true
    daemon_reload: "{{ headless_reboot_units.changed }}"

- name: Configure DNF to download in parallel
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: max_parallel_downloads
    value: "3"
    mode: "0644"
