---
- name: install dnf-automatic
  dnf:
    name: dnf-automatic
  register: task
  until: task is succeeded
  retries: 20
  delay: 0

- name: configure dnf-automatic
  template:
    src: etc/dnf/automatic.conf
    dest: /etc/dnf/automatic.conf
    mode: 0644
    owner: root
    group: root

- name: ensure dnf-automatic is running
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true

- name: schedule automatic reboots when necessary
  template:
    src: etc/systemd/system/{{ unit }}
    dest: /etc/systemd/system/{{ unit }}
  loop:
  - reboot.service
  - reboot.timer
  loop_control:
    loop_var: unit
  register: reboot_units

- name: enable scheduled reboots
  systemd:
    name: reboot.timer
    state: started
    enabled: true
    daemon_reload: "{{ reboot_units.changed }}"
