---
- name: install the dnf local plugin
  dnf:
    name:
    - python3-dnf-plugin-local
    - nfs-utils
    - autofs

- name: create repodir base mount location
  file:
    path: /mnt/dnf
    state: directory

- name: configure autofs to mount dnf lazily
  lineinfile:
    path: /etc/auto.master
    line: /mnt /etc/auto.nfs --timeout=900
    regexp: '^/mnt '
    owner: root
    group: root

- name: mount dnf repo from NAS
  lineinfile:
    path: /etc/auto.nfs
    create: true
    line: "dnf -fstype=nfs,rw,sync,intr,tcp,timeo=20,rsize=32000,wsize=32000 stuffbox.lan:/volume1/dnf"

- name: create repodir for distro
  file:
    path: /mnt/dnf/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/
    state: directory
  register: repodir

- name: initialize repodir
  command: createrepo /mnt/dnf/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}
  when: repodir is changed

- name: enable dnf local plugin
  ini_file:
    path: /etc/dnf/plugins/local.conf
    section: main
    option: enabled
    value: "true"

- name: configure dnf local plugin repo
  ini_file:
    path: /etc/dnf/plugins/local.conf
    section: main
    option: repodir
    value: /mnt/dnf/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}

- name: enable createrepo
  ini_file:
    path: /etc/dnf/plugins/local.conf
    section: createrepo
    option: enabled
    value: "true"

- name: configure createrepo cache dir
  ini_file:
    path: /etc/dnf/plugins/local.conf
    section: createrepo
    option: cachedir
    value: /tmp/createrepo-local-plugin-cachedir
