---
- name: install the dnf local plugin
  dnf:
    name:
    - python3-dnf-plugin-local
    - nfs-utils
    - autofs

- name: ensure we're not mounting anything directly to /mnt
  lineinfile:
    path: /etc/auto.master
    regexp: '^/mnt '
    state: absent
    owner: root
    group: root
  register: remove_mnt

- name: remove auto.master
  lineinfile:
    path: /etc/auto.master
    regexp: '^\+auto.master$'
    state: absent
    owner: root
    group: root
  register: remove_auto_master

- name: restart autofs
  systemd:
    name: autofs
    state: restarted
  when: remove_mnt is changed or remove_auto_master is changed

- name: create repodir base mount location
  file:
    path: /mnt/nfs/
    state: directory

- name: configure autofs to mount nfs lazily
  lineinfile:
    path: /etc/auto.master
    line: /mnt/nfs /etc/auto.nfs --timeout=900
    regexp: '^/mnt/nfs '
    owner: root
    group: root

- name: mount dnf repo from NAS
  lineinfile:
    path: /etc/auto.nfs
    create: true
    line: "dnf -fstype=nfs,rw,sync,intr,tcp,timeo=20,rsize=32000,wsize=32000 pizzabox.lan:/volume1/dnf"

- name: enable autofs
  systemd:
    name: autofs
    enabled: true
    state: started

- name: create repodir for distro
  file:
    path: /mnt/nfs/dnf/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/
    state: directory
  register: repodir

- name: initialize repodir
  command: createrepo /mnt/nfs/dnf/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}
  when: repodir is changed

- name: enable dnf local plugin
  ini_file:
    path: /etc/dnf/plugins/local.conf
    section: main
    option: enabled
    value: "true"

- name: configure dnf local plugin repo
  ini_file:
    path: /etc/dnf/plugins/local.conf
    section: main
    option: repodir
    value: /mnt/nfs/dnf/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}

- name: enable createrepo
  ini_file:
    path: /etc/dnf/plugins/local.conf
    section: createrepo
    option: enabled
    value: "true"

- name: configure createrepo cache dir
  ini_file:
    path: /etc/dnf/plugins/local.conf
    section: createrepo
    option: cachedir
    value: /tmp/createrepo-local-plugin-cachedir
