---
- name: ensure docker is uninstalled
  dnf:
    name:
    - containerd.io
    - docker
    - docker-ce
    - docker-ce-cli
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-engine
    - docker-engine-selinux
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    state: absent

- name: disable docker repo
  yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/fedora/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/stable/
    description: Docker Community Edition
    state: absent

- name: untrust docker's gpg key
  rpm_key:
    key: https://download.docker.com/linux/fedora/gpg
    fingerprint: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35
    state: absent

# Can/should this be undone?
# - name: enable backwards compatibility for cgroups
#   command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
#   when: ansible_distribution == 'Fedora'

- name: remove docker group
  group:
    name: docker
    state: absent
