- name: trust github.com
  lineinfile:
    path: "/home/{{ whoami }}/.ssh/known_hosts"
    line: "{{ item }}"
    create: true
    mode: 0644
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  loop:
  - "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  - "[ssh.github.com]:443,[192.30.253.122]:443 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  tags:
  - known-hosts

- name: install git and friends on arch
  pacman:
    name:
    - gist
    - git
    - hub
  when: ansible_distribution == 'Archlinux'

- name: install git and friends on ubuntu
  apt:
    name:
    - gist
    - git
    force_apt_get: true
  when: ansible_distribution == 'Ubuntu'

- name: install git and friends on fedora
  yum:
    name:
    - git
    - hub
  when: ansible_distribution == 'Fedora'

- name: install hub
  snap:
    name:
    - hub
    classic: true
  when: ansible_distribution == 'Ubuntu'

- name: configure hub
  template:
    src: home/config/hub
    dest: "/home/{{ whoami }}/.config/hub"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"

- name: configure git, gist
  template:
    src: "home/{{ item }}"
    dest: "/home/{{ whoami }}/.{{ item }}"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  with_items:
  - gitconfig
  - gitignore_global
  - gist
