---
- name: Discover latest release tag of {{ github_release_binary }}
  community.general.github_release:
    user: "{{ github_release_user }}"
    repo: "{{ github_release_binary }}"
    action: latest_release
  register: headless_github_release

- name: Install from github {{ github_release_binary }}
  vars:
    headless_github_release_base: "https://github.com/{{ github_release_user }}/{{ github_release_binary }}"
    headless_github_release_url: "{{ headless_github_release_base }}/releases/download/{{ headless_github_release.tag }}/{{ github_release_binary }}"
  ansible.builtin.get_url:
    url: "{{ headless_github_release_url }}"
    dest: /home/{{ whoami }}/bin/{{ github_release_binary }}
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0770"
    force: true
