- name: install golang
  dnf:
    name: golang

- name: create GOPATH
  file:
    path: "/home/{{ whoami }}/go"
    state: directory
    owner: "{{ whoami }}"
    group: "{{ whoami }}"

- name: install vim-go plugins
  become: true
  become_user: "{{ whoami }}"
  command: nvim +GoInstallBinaries +qall
  no_log: true # prevent vim from messing with ansible's stdout/stderr
