- name: install go on arch
  pacman:
    name: go
  when: ansible_distribution == 'Archlinux'

- name: install go on ubuntu
  apt:
    name: golang
    force_apt_get: true
  when: ansible_distribution == 'Ubuntu'

- name: install go on fedora
  yum:
    name: golang
  when: ansible_distribution == 'Fedora'

- name: create GOPATH
  file:
    path: /home/dolph/go
    state: directory
    owner: dolph
    group: dolph

- name: install vim-go plugins
  become: true
  become_user: dolph
  command: vim +GoInstallBinaries! +qall
  when: ansible_distribution != 'Fedora'

- name: install vim-go plugins
  become: true
  become_user: dolph
  command: gvim -v +GoInstallBinaries! +qall
  when: ansible_distribution == 'Fedora'
