---
- name: Discover latest version of kubectl
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  check_mode: false
  register: headless_kubectl_version

- name: Install kubectl
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/{{ headless_kubectl_version.content }}/bin/linux/amd64/kubectl
    dest: /home/{{ whoami }}/bin/kubectl
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0770"
    force: true

- name: Install krew
  block:
    - name: Create temp dir to extract krew
      become: true
      become_user: "{{ whoami }}"
      ansible.builtin.tempfile:
        state: directory
      register: headless_krew_tempdir

    - name: Extract krew
      become: true
      become_user: "{{ whoami }}"
      ansible.builtin.unarchive:
        src: https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-linux_amd64.tar.gz
        remote_src: true
        dest: "{{ headless_krew_tempdir.path }}"
      when: headless_krew_tempdir.path is defined # not defined in check mode

    - name: Use krew to install krew
      become: true
      become_user: "{{ whoami }}"
      ansible.builtin.command: "{{ headless_krew_tempdir.path }}/krew-linux_amd64 install krew"
      changed_when: true
      when: headless_krew_tempdir.path is defined # not defined in check mode

  always:
    - name: Remove krew temp dir
      ansible.builtin.file:
        path: "{{ headless_krew_tempdir.path }}"
        state: absent
      changed_when: false
      when: headless_krew_tempdir.path is defined # not defined in check mode

- name: Install kube plugins
  become: true
  become_user: "{{ whoami }}"
  ansible.builtin.shell: "source /home/{{ whoami }}/.profile; /home/{{ whoami }}/bin/kubectl krew install {{ plugin }}"
  register: headless_task
  changed_when: '"Skipping plugin" is not in headless_task.stdout'
  loop:
    - ctx
    - ns
  loop_control:
    loop_var: plugin

# install tekton https://github.com/tektoncd/cli/releases

- name: Install python3-github3 to help discover github release versions
  ansible.builtin.dnf:
    name: python3-github3py

- name: Discover the latest release tag of tekton
  community.general.github_release:
    user: tektoncd
    repo: cli
    action: latest_release
  register: headless_latest_tekton_release

- name: Install tekton
  block:
    - name: Create temp dir to extract tekton
      ansible.builtin.tempfile:
        state: directory
      register: headless_tekton_tempdir

    - name: Extract tekton
      ansible.builtin.unarchive:
        src: https://github.com/tektoncd/cli/releases/latest/download/tkn_{{ headless_latest_tekton_release.tag.lstrip('v') }}_Linux_x86_64.tar.gz
        remote_src: true
        dest: "{{ headless_tekton_tempdir.path }}"

    - name: Check for tkn binary
      ansible.builtin.stat:
        path: "{{ headless_tekton_tempdir.path }}/tkn"
      register: headless_tkn

    - name: Use tekton to install tekton
      ansible.builtin.copy:
        remote_src: true
        src: "{{ headless_tekton_tempdir.path }}/tkn"
        dest: /home/{{ whoami }}/bin/
        owner: "{{ whoami }}"
        group: "{{ whoami }}"
        mode: "0770"
      when:
        - headless_tkn.stat.exists is defined

  always:
    - name: Remove tekton temp dir
      ansible.builtin.file:
        path: "{{ headless_tekton_tempdir.path }}"
        state: absent
      changed_when: false
