---
- name: whoami
  set_fact:
    whoami: "{{ lookup('env', 'USER') | default('dolph', true) }}"
  tags:
  - always
  - whoami

- name: ensure user exists
  user:
    name: "{{ whoami }}"

- name: check for local public key
  find:
    paths: /home/{{ whoami }}/.ssh/
    patterns: id_*.pub
  register: public_keys
  tags: access

- name: authorize local user to access remote user
  authorized_key:
    user: "{{ whoami }}"
    key: "{{ lookup('file', public_key.path).rsplit(' ', 1)[0] }}"
  loop: "{{ public_keys.files }}"
  loop_control:
    loop_var: public_key
  tags: access

- name: fetch public github keys
  uri:
    url: https://github.com/dolph.keys
    return_content: true
  check_mode: false  # force this task to run, even in check mode
  register: github_keys
  tags: access

- name: trust public github keys to access remote user
  authorized_key:
    user: "{{ whoami }}"
    key: "{{ key }}"
  loop: "{{ github_keys.content.splitlines() }}"
  loop_control:
    loop_var: key
  when: github_keys.status == 200
  tags: access

- name: allow passwordless sudo
  template:
    src: etc/sudoers.d/whoami
    dest: "/etc/sudoers.d/{{ whoami }}"
    mode: 0400

- name: configure automated upgrades
  import_tasks: automated-upgrades.yml
  tags:
  - dnf
  - dnf-automatic

- name: configure ssh client
  import_tasks: ssh-client.yml
  tags:
  - ssh
  - ssh-client

- name: configure ssh server
  import_tasks: ssh-server.yml
  tags:
  - ssh-server
  - ssh

- name: configure terminal
  import_tasks: terminal.yml
  tags: terminal

- name: configure git
  import_tasks: git.yml
  tags: git

- name: configure travis
  import_tasks: travis.yml
  tags: travis

- name: configure editor
  import_tasks: vim.yml
  tags: vim

- name: configure go
  import_tasks: go.yml
  tags: go

- name: configure terminal multiplexer
  import_tasks: tmux.yml
  tags: tmux

- name: configure ripgrep
  import_tasks: ripgrep.yml
  tags:
  - ripgrep
  - rg

- name: configure python
  import_tasks: python.yml
  tags: python

- name: install additional packages
  dnf:
    name:
    - autossh
    - curl
    - dnf-plugin-system-upgrade
    - htop
    - jq
    - neofetch
    - sshpass
    - tree

- name: create a bin directory
  file:
    path: "/home/{{ whoami }}/bin"
    state: directory
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  tags:
  - bin

- name: populate bin dir
  copy:
    src: "bin/{{ item }}"
    dest: "/home/{{ whoami }}/bin"
    mode: 0770
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  loop:
  - a
  - benchmark
  - enc
  - fail
  - gac
  - gacp
  - gap
  - gcp
  - git-delete-merged-branches
  - git-list-merged-branches
  - git-pr
  - git-ready
  - git-recommit
  - git-rmcommit
  - git-uncommit
  - icanhazip
  - loop
  - n
  - name
  - release-upgrade
  - try
  - upgrade
  - uplink-monitor
  - uuid
  tags:
  - bin

- name: install binaries from github
  get_url:
    url: https://github.com/dolph/{{ binary }}/releases/latest/download/{{ binary }}
    dest: /home/{{ whoami }}/bin/{{ binary }}
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: 0770
  loop:
  - find-replace
  - txt
  loop_control:
    loop_var: binary
  tags:
  - bin
  - find-replace
  - txt

- name: install podman
  import_tasks: podman.yml
  tags: podman
