---
- name: Whoami
  ansible.builtin.set_fact:
    whoami: "{{ lookup('env', 'USER') | default('dolph', true) }}"
  tags:
  - always
  - whoami

- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ whoami }}"

- name: Check for local public key
  ansible.builtin.find:
    paths: /home/{{ whoami }}/.ssh/
    patterns: id_*.pub
  register: public_keys
  tags: access

- name: Authorize local user to access remote user
  ansible.posix.authorized_key:
    user: "{{ whoami }}"
    key: "{{ lookup('file', public_key.path).rsplit(' ', 1)[0] }}"
  loop: "{{ public_keys.files }}"
  loop_control:
    loop_var: public_key
  tags: access

- name: Fetch public github keys
  ansible.builtin.uri:
    url: https://github.com/dolph.keys
    return_content: true
  check_mode: false  # force this task to run, even in check mode
  register: github_keys
  tags: access

- name: Trust public github keys to access remote user
  ansible.posix.authorized_key:
    user: "{{ whoami }}"
    key: "{{ key }}"
  loop: "{{ github_keys.content.splitlines() }}"
  loop_control:
    loop_var: key
  when: github_keys.status == 200
  tags: access

- name: Allow passwordless sudo
  ansible.builtin.template:
    src: etc/sudoers.d/whoami
    dest: "/etc/sudoers.d/{{ whoami }}"
    mode: 0400

- name: Configure automated upgrades
  ansible.builtin.import_tasks: automated-upgrades.yml
  tags:
  - dnf
  - dnf-automatic

- name: Configure ssh client
  ansible.builtin.import_tasks: ssh-client.yml
  tags:
  - ssh
  - ssh-client

- name: Configure ssh server
  ansible.builtin.import_tasks: ssh-server.yml
  tags:
  - ssh-server
  - ssh

- name: Configure terminal
  ansible.builtin.import_tasks: terminal.yml
  tags: terminal

- name: Configure git
  ansible.builtin.import_tasks: git.yml
  tags: git

- name: Configure ripgrep
  ansible.builtin.import_tasks: ripgrep.yml
  tags:
  - ripgrep
  - rg

- name: Configure editor
  ansible.builtin.import_tasks: vim.yml
  tags: vim

- name: Configure go
  ansible.builtin.import_tasks: go.yml
  tags: go

- name: Configure terminal multiplexer
  ansible.builtin.import_tasks: tmux.yml
  tags: tmux

- name: Configure python
  ansible.builtin.import_tasks: python.yml
  tags: python

- name: Install additional packages
  ansible.builtin.dnf:
    name:
    - autossh
    - curl
    - dnf-plugin-system-upgrade
    - htop
    - jq
    - qalculate
    - sshpass
    - tree
    - inotify-tools

- name: Create a bin directory
  ansible.builtin.file:
    path: "/home/{{ whoami }}/bin"
    state: directory
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  tags:
  - bin

- name: Populate bin dir
  ansible.builtin.copy:
    src: "bin/{{ item }}"
    dest: "/home/{{ whoami }}/bin"
    mode: 0770
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  loop:
  - benchmark
  - c
  - enc
  - fail
  - gac
  - gacp
  - gap
  - gcp
  - git-clone-org
  - git-delete-merged-branches
  - git-list-merged-branches
  - git-pr
  - git-ready
  - git-recommit
  - git-rmcommit
  - git-uncommit
  - gp
  - grs
  - icanhazip
  - loop
  - n
  - name
  - release-upgrade
  - post-release-upgrade
  - try
  - upgrade
  - uuid
  - vif
  - vig
  tags:
  - bin

- name: Install binaries from github
  ansible.builtin.get_url:
    url: https://github.com/dolph/{{ binary }}/releases/latest/download/{{ binary }}
    dest: /home/{{ whoami }}/bin/{{ binary }}
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: 0770
  loop:
  - find-replace
  - txt
  - connectivity
  loop_control:
    loop_var: binary
  tags:
  - bin
  - find-replace
  - txt

- name: Install podman
  ansible.builtin.import_tasks: podman.yml
  tags: podman

- name: Install kubernetes
  ansible.builtin.import_tasks: kube.yml
  tags:
  - kube
  - k8s
  - kubernetes
