- name: install container tools
  dnf:
    name:
    - podman
    - buildah

- name: authenticate with dockerhub
  command:
    cmd: podman login --username {{ dockerhub_username }} --password {{ dockerhub_token }}
