- name: install python dependencies
  dnf:
    name:
    - python3-virtualenv
    - python3-devel
    - python3-flake8

- name: configure flake8
  template:
    src: home/flake8
    dest: "/home/{{ whoami }}/.flake8"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"

- name: install virtualenvwrapperlite
  become: true
  become_user: "{{ whoami }}"
  git:
    repo: https://github.com/dolph/virtualenvwrapperlite.git
    dest: "/home/{{ whoami }}/.virtualenvwrapperlite"
