---
- name: Install python dependencies
  ansible.builtin.dnf:
    name:
      - python3-virtualenv
      - python3-devel
      - python3-flake8

- name: Configure flake8
  ansible.builtin.template:
    src: home/flake8
    dest: "/home/{{ whoami }}/.flake8"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0600"

- name: Install virtualenvwrapperlite # noqa: latest[git]
  become: true
  become_user: "{{ whoami }}"
  ansible.builtin.git:
    repo: https://github.com/dolph/virtualenvwrapperlite.git
    dest: "/home/{{ whoami }}/.virtualenvwrapperlite"
