- name: install virtualenv on arch
  pacman:
    name: python-virtualenv
  when: ansible_distribution == 'Archlinux'

- name: install virtualenv on ubuntu
  apt:
    name: python-virtualenv
    force_apt_get: true
  when: ansible_distribution == 'Ubuntu'

- name: install python dependencies on fedora
  yum:
    name:
    - python3-virtualenv
    - python3-devel
    - python3-flake8
  when: ansible_distribution == 'Fedora'

- name: configure flake8
  template:
    src: home/flake8
    dest: /home/dolph/.flake8
    owner: dolph
    group: dolph

- name: install virtualenvwrapperlite
  become: true
  become_user: dolph
  git:
    repo: https://github.com/dolph/virtualenvwrapperlite.git
    dest: /home/dolph/.virtualenvwrapperlite
