- name: Install ripgrep
  ansible.builtin.dnf:
    name: ripgrep

- name: Configure ripgrep
  ansible.builtin.template:
    src: home/ripgreprc
    dest: "/home/{{ whoami }}/.ripgreprc"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0600"
