- name: install ripgrep on arch
  pacman:
    name: ripgrep
  when: ansible_distribution == 'Archlinux'

- name: install ripgrep on ubuntu
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
  when: ansible_distribution == 'Ubuntu'

- name: install ripgrep on fedora
  yum:
    name: ripgrep
  when: ansible_distribution == 'Fedora'

- name: configure ripgrep
  template:
    src: home/ripgreprc
    dest: /home/dolph/.ripgreprc
    owner: dolph
    group: dolph
