- name: install ripgrep
  dnf:
    name: ripgrep

- name: configure ripgrep
  template:
    src: home/ripgreprc
    dest: "/home/{{ whoami }}/.ripgreprc"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
