---
- name: Create ssh directory
  ansible.builtin.file:
    path: "/home/{{ whoami }}/.ssh"
    state: directory
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0700"

- name: Create an SSH config file
  ansible.builtin.command: touch "/home/{{ whoami }}/.ssh/config"
  args:
    creates: "/home/{{ whoami }}/.ssh/config"

- name: Set ssh config permissions
  ansible.builtin.file:
    path: "/home/{{ whoami }}/.ssh/config"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0600"
