- name: create ssh directory
  file:
    path: "/home/{{ whoami }}/.ssh"
    state: directory
    owner: "{{ whoami }}"
    group: "{{ whoami }}"

- name: create an SSH config file
  command: touch "/home/{{ whoami }}/.ssh/config"
  args:
    creates: "/home/{{ whoami }}/.ssh/config"

- name: set ssh config permissions
  file:
    path: "/home/{{ whoami }}/.ssh/config"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: 0600
