---
- name: Remove bash-preexec
  ansible.builtin.file:
    path: "/home/{{ whoami }}/.bash-preexec"
    state: absent

- name: Configure terminal
  ansible.builtin.template:
    src: "home/{{ item }}"
    dest: "/home/{{ whoami }}/.{{ item }}"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0600"
  with_items:
  - bash_profile
  - bash_prompt
  - bashrc
  - inputrc
  - profile
  tags:
  - terminal
  - bashrc

- name: Ensure bash_prompt is executable
  ansible.builtin.file:
    path: "/home/{{ whoami }}/.bash_prompt"
    mode: 0755

- name: Ensure a localrc exists
  ansible.builtin.copy:
    content: ""
    dest: "/home/{{ whoami }}/.localrc"
    force: false
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0600"
  tags:
  - terminal
  - localrc
