---
- name: remove bash-preexec
  file:
    path: "/home/{{ whoami }}/.bash-preexec"
    state: absent

- name: configure terminal
  template:
    src: "home/{{ item }}"
    dest: "/home/{{ whoami }}/.{{ item }}"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  with_items:
  - bash_profile
  - bash_prompt
  - bashrc
  - inputrc
  - profile
  tags:
  - terminal
  - bashrc

- name: ensure bash_prompt is executable
  file:
    path: "/home/{{ whoami }}/.bash_prompt"
    mode: 0755

- name: ensure a localrc exists
  copy:
    content: ""
    dest: "/home/{{ whoami }}/.localrc"
    force: false
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  tags:
  - terminal
  - localrc
