---
- name: install ripgrep
  dnf:
    name: dnf-plugins-core

- name: trust the google linux packaging GPG key
  ansible.builtin.rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    fingerprint: 4CCA 1EAF 950C EE4A B839 76DC A040 830F 7FAC 5991

- name: Add Hashicorp repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp stable repo
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: install terraform
  dnf:
    name: terraform

- name: validate terraform install
  command: terraform -help
  changed_when: false
