- name: install tmux
  dnf:
    name:
    - tmux
    - xclip

- name: create tmux plugins dir
  become: true
  become_user: "{{ whoami }}"
  file:
    path: ~/.tmux-plugins
    state: directory

- name: install tmux plugins
  become: true
  become_user: "{{ whoami }}"
  git:
    repo: "https://github.com/tmux-plugins/tmux-{{ item }}.git"
    dest: "~/.tmux-plugins/{{ item }}"
  register: git_result
  with_items:
  - battery
  - copycat
  - cpu
  - net-speed
  - open
  - yank

- name: configure tmux
  template:
    src: home/tmux.conf
    dest: "/home/{{ whoami }}/.tmux.conf"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
  register: tmux_conf
  tags: configure-tmux

- name: check if tmux is running
  become: true
  become_user: "{{ whoami }}"
  command: tmux info
  failed_when: false
  changed_when: false
  check_mode: false # Force this task to run, even in check mode.
  register: tmux_running

- name: apply tmux config
  become: true
  become_user: "{{ whoami }}"
  command: "tmux source-file /home/{{ whoami }}/.tmux.conf"
  when: tmux_conf.changed and tmux_running.rc == 0
