---
- name: Install tmux
  ansible.builtin.dnf:
    name:
      - tmux
      - xclip

- name: Uninstall xsel
  ansible.builtin.dnf:
    name:
      - xsel
    state: absent

- name: Create tmux plugins dir
  become: true
  become_user: "{{ whoami }}"
  ansible.builtin.file:
    path: ~/.tmux-plugins
    state: directory
    mode: "0700"

- name: Install tmux plugins # noqa: latest[git]
  become: true
  become_user: "{{ whoami }}"
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tmux-{{ item }}.git"
    dest: "~/.tmux-plugins/{{ item }}"
  register: headless_git_result
  with_items:
    - battery
    - copycat
    - cpu
    - net-speed
    - open
    - yank

- name: Configure tmux
  ansible.builtin.template:
    src: home/tmux.conf
    dest: "/home/{{ whoami }}/.tmux.conf"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: "0600"
  register: headless_tmux_conf
  tags: configure-tmux

- name: Check if tmux is running
  become: true
  become_user: "{{ whoami }}"
  ansible.builtin.command: tmux info
  failed_when: false
  changed_when: false
  check_mode: false # Force this task to run, even in check mode.
  register: headless_tmux_running

- name: Apply tmux config
  become: true
  become_user: "{{ whoami }}"
  ansible.builtin.command: "tmux source-file /home/{{ whoami }}/.tmux.conf"
  changed_when: true
  when: headless_tmux_conf.changed and headless_tmux_running.rc == 0
