- name: install vagrant and plugins
  dnf:
    name:
    - vagrant
    - vagrant-registration

- name: configure red hat vagrant plugin
  blockinfile:
    path: /home/{{ whoami }}/.vagrant.d/Vagrantfile
    marker: "# {mark} ANSIBLE MANAGED RED HAT SUBSCRIPTION BLOCK"
    create: true
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    block: |
      Vagrant.configure('2') do |config|
        config.registration.username = '{{ redhat_subscription_username }}'
        config.registration.password = '{{ redhat_subscription_password }}'
      end
