- name: uninstall vim
  dnf:
    name:
    - vim
    - vim-enhanced
    state: absent

- name: install gvim (to get X11 clipboard support)
  dnf:
    name: vim-X11

- name: configure vim
  template:
    src: home/vimrc
    dest: "/home/{{ whoami }}/.vimrc"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"

- name: install vim plugin manager
  become: true
  become_user: "{{ whoami }}"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: install gvim plugins
  become: true
  become_user: "{{ whoami }}"
  command: gvim -v +PluginInstall! +PluginClean! +qall
  no_log: true # prevent vim from messing with ansible's stdout/stderr
