---
# https://copr.fedorainfracloud.org/
- name: check enabled community repos
  command: dnf copr list --enabled
  args:
    warn: false
  changed_when: false
  register: enabled_copr_repos
  when:
  - ansible_distribution == 'Fedora'
  - ansible_distribution_major_version | int == 31

# https://copr.fedorainfracloud.org/
- name: enable wireguard community repo
  command: dnf copr enable -y jdoss/wireguard
  args:
    warn: false
  when:
  - ansible_distribution == 'Fedora'
  - ansible_distribution_major_version | int == 31
  - "'jdoss/wireguard' not in enabled_copr_repos.stdout"

- name: install kernel dev stuff
  dnf:
    name:
    - kernel-headers
    - kernel-devel
  when: ansible_distribution == 'Fedora'
  register: task
  until: task is succeeded
  retries: 3
  delay: 0

- name: install wireguard on Fedora 31
  dnf:
    name:
    - wireguard-dkms
    - wireguard-tools
  when:
  - ansible_distribution == 'Fedora'
  - ansible_distribution_major_version | int == 31
  register: task
  until: task is succeeded
  retries: 3
  delay: 0

- name: install wireguard on Fedora 32+
  dnf:
    name:
    - wireguard-tools
  when:
  - ansible_distribution == 'Fedora'
  - ansible_distribution_major_version | int >= 32
  register: task
  until: task is succeeded
  retries: 3
  delay: 0

- name: install iptables on gateway
  dnf:
    name:
    - iptables-services
  when:
  - ansible_distribution == 'Fedora'
  - wireguard_ip.endswith('.1')
  register: task
  until: task is succeeded
  retries: 3
  delay: 0

- name: enable iptables on gateway
  systemd:
    name: iptables
    enabled: true
    state: started
  when:
  - ansible_distribution == 'Fedora'
  - wireguard_ip.endswith('.1')
  register: task
  until: task is succeeded
  retries: 3
  delay: 0

- name: create config dir
  file:
    path: /etc/wireguard/
    state: directory
    mode: 0600

- name: generate private key
  shell: umask 077; wg genkey > /etc/wireguard/private
  args:
    creates: /etc/wireguard/private

- name: ensure private key is protected correctly
  file:
    path: /etc/wireguard/private
    mode: 0600

- name: read private key
  slurp:
    src: /etc/wireguard/private
  changed_when: false
  register: wireguard_private_key
  tags: wireguard-config

- name: set private key variable
  set_fact:
    wireguard_private_key: "{{ wireguard_private_key.content | b64decode }}"
  tags: wireguard-config

- name: generate public key from private key
  shell: wg pubkey < /etc/wireguard/private
  changed_when: false
  check_mode: false
  register: wireguard_public_key
  tags: wireguard-config

- name: set public key variable
  set_fact:
    wireguard_public_key: "{{ wireguard_public_key.stdout }}"
  tags: wireguard-config

- name: backup encrypted wireguard-peers locally
  become: true
  become_user: "{{ whoami }}"
  delegate_to: localhost
  run_once: true
  copy:
    src: vars/wireguard-peers
    dest: vars/wireguard-peers.backup
    decrypt: false
  changed_when: false

- name: decrypt wireguard-peers locally
  become: true
  become_user: "{{ whoami }}"
  delegate_to: localhost
  run_once: true
  command: /home/{{ whoami }}/venv/ansible/bin/ansible-vault decrypt vars/wireguard-peers
  changed_when: false

- name: write peer to local file
  become: true
  become_user: "{{ whoami }}"
  local_action:
    module: lineinfile
    line: "- {'hostname': '{{ ansible_hostname }}', 'wireguard_ip': '{{ wireguard_ip }}', 'ip': '{{ ansible_default_ipv4.address }}', 'public_key': '{{ wireguard_public_key }}'}"
    path: vars/wireguard-peers
    regexp: "^\ {'wireguard_ip':\ '{{ wireguard_ip }}',\ "
  register: peers

- name: re-encrypt wireguard-peers locally
  become: true
  become_user: "{{ whoami }}"
  delegate_to: localhost
  run_once: true
  command: /home/{{ whoami }}/venv/ansible/bin/ansible-vault encrypt vars/wireguard-peers
  when: peers.changed
  changed_when: false

- name: restore wireguard-peers locally
  become: true
  become_user: "{{ whoami }}"
  delegate_to: localhost
  run_once: true
  copy:
    src: vars/wireguard-peers.backup
    dest: vars/wireguard-peers
    decrypt: false
  when: not peers.changed
  changed_when: false

- name: remove wireguard-peers local backup
  become: true
  become_user: "{{ whoami }}"
  delegate_to: localhost
  run_once: true
  file:
    path: vars/wireguard-peers.backup
    state: absent
  changed_when: false

- name: reload wireguard peers
  include_vars:
    file: vars/wireguard-peers
  tags:
  - ping-wireguard-peers
  - wireguard-config

- name: push wireguard config
  template:
    src: etc/wireguard/wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: 0600
  register: wireguard_conf
  tags: wireguard-config

- name: stop wireguard
  command: wg-quick down wg0
  register: task
  failed_when: task is not succeeded and 'is not a WireGuard interface' not in task.stderr
  changed_when: "'ip link delete dev wg0' in task.stderr"

- name: enable wireguard
  command: wg-quick up wg0
  register: task
  failed_when: task is not succeeded and 'already exists' not in task.stderr
  changed_when: "'ip link add wg0 type wireguard' in task.stderr"
  when:
  - wireguard_peers | length >= 2

- name: test connectivity to peers (and self)
  command: "ping -c 1 {{ item.wireguard_ip }}"
  loop: "{{ wireguard_peers }}"
  loop_control:
    label: "{{ item.hostname }} ({{ item.wireguard_ip }})"
  changed_when: true
  register: task
  until: task.rc == 0
  retries: 1
  delay: 0
  tags: ping-wireguard-peers
