# https://alacritty.org/config-alacritty.html

[scrolling]
history = 100000
multiplier = 1

[font]
size = {{ font_size }}
normal = { family = "Hack", style = "Bold" }

[colors]

[colors.primary]
foreground = "#839496"
background = "#000000"

[colors.normal]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[colors.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Tab", mods = "Control", command = { program = "tmux", args = ["select-window", "-t", "+"] } },
    { key = "Tab", mods = "Shift|Control", command = { program = "tmux", args = ["select-window", "-t", "-" ] } },
    { key = "C", mods = "Shift|Control", action = "Copy" },
    { key = "V", mods = "Shift|Control", action = "Paste" },
]

# URxvt.keysym.Shift-Control-V: eval:paste_clipboard
# URxvt.keysym.Shift-Control-C: eval:selection_to_clipboard
