#!/bin/bash

# Priorities.
export EDITOR="gvim -v"
alias e="gvim -v"
alias vi="gvim -v"
alias vim="gvim -v"

alias q="exit"
alias gist="gist-paste"
alias watch="watch --color --differences"

# Shortcut to open a SOCKS proxy
alias proxy="ssh -D 8123 -q -N"

# pyc files are annoying
export PYTHONDONTWRITEBYTECODE=1

# [time] hostname:workdir $
export PS1="[\[\033[36m\]\t\[\033[39m\]] \[\033[34m\]\h\[\033[39m\]:\[\033[33m\]\w \[\033[32m\]\\$ \[\033[40m\]\[$(tput sgr0)\]\[\033[39m\]"

# Enable color file listings.
alias ls='ls --almost-all --classify --color=auto'

# Set virtualenv shortcuts.
export WORKON_HOME=$HOME/venv
. ~/.virtualenvwrapperlite/virtualenvwrapperlite.sh

# Configure ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

function ssh-unlock() {
    if [ -n "$TMUX" ]; then
        if [ -z ${SSH_AGENT_PID+x} ] || [ ! "ps -p ${SSH_AGENT_PID} > /dev/null" ]; then
            eval "$(ssh-agent -s)" > /dev/null
            ssh-add $(ls $HOME/.ssh/*.pub | xargs | sed 's/.pub//g') &> /dev/null
        fi
    fi
}
ssh-unlock

{% if txt_twilio_account_sid is defined %}
export TXT_TWILIO_ACCOUNT_SID="{{ txt_twilio_account_sid }}"
export TXT_TWILIO_AUTH_TOKEN="{{ txt_twilio_auth_token }}"
export TXT_TO="{{ txt_to }}"
export TXT_TWILIO_FROM="{{ txt_twilio_from }}"
{% endif %}

{% if redhat_subscription_password is defined %}
# Red Hat subscription (used by Vagrant)
export SUB_USERNAME='{{ redhat_subscription_username }}'
export SUB_PASSWORD='{{ redhat_subscription_password }}'
{% endif %}

# Allow local account customization
. $HOME/.localrc
