#!/bin/bash

{% if ansible_distribution == 'Fedora' %}
# Priorities.
export EDITOR="gvim -v"
alias e="gvim -v"
alias vi="gvim -v"
alias vim="gvim -v"
{% else %}
export EDITOR="vim"
alias e="vim"
{% endif %}

alias q="exit"

alias gist="gist-paste"

# Shortcut to open a SOCKS proxy
alias proxy="ssh -D 8123 -q -N"

# pyc files are annoying
export PYTHONDONTWRITEBYTECODE=1

# default: PS1='\h:\W \u\$'
# hostname cwd $
export PS1="[\[\033[36m\]\t\[\033[39m\]] \[\033[32m\]\u\[\033[39m\]@\[\033[34m\]\h\[\033[39m\]:\[\033[33m\]\w\n\[\033[33m\]\\$ \[\033[40m\]\[$(tput sgr0)\]\[\033[39m\]"
# cwd $
# export PS1="\[\033[32m\]\W \[\033[34m\]\\$ \[\033[34m\]\[$(tput sgr0)\]\[\033[96m\]"

# Enable color file listings.
alias ls='ls --almost-all --classify --color=auto'

# Set virtualenv shortcuts.
export WORKON_HOME=$HOME/venv
. ~/.virtualenvwrapperlite/virtualenvwrapperlite.sh

# Configure ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

function ssh-unlock() {
    if [ -n "$TMUX" ]; then
        if [ -z ${SSH_AGENT_PID+x} ] || [ ! "ps -p ${SSH_AGENT_PID} > /dev/null" ]; then
            eval "$(ssh-agent -s)" > /dev/null
            ssh-add $(ls $HOME/.ssh/*.pub | xargs | sed 's/.pub//g')
        fi
    fi
}
ssh-unlock

{% if txt_twilio_account_sid is defined %}
export TXT_TWILIO_ACCOUNT_SID="{{ txt_twilio_account_sid }}"
export TXT_TWILIO_AUTH_TOKEN="{{ txt_twilio_auth_token }}"
export TXT_TO="{{ txt_to }}"
export TXT_TWILIO_FROM="{{ txt_twilio_from }}"
{% endif %}

# Automatically jump into an existing tmux session.
if [ -z "$TMUX" ]; then
    tmux attach -d || tmux new
fi

# Allow local account customization
. $HOME/.localrc

# Define preexec / precmd to keep tmux environment updated when reattaching.
if [ -n "$TMUX" ]; then
    function refresh {
        export $(tmux show-environment | grep "^WINDOWID")
    }
else
    function refresh {
        :
    }
fi
function preexec {
    refresh
}
function precmd {
    refresh
}

# Enable precmd and preexec support
source $HOME/.bash-preexec/bash-preexec.sh
