" change the leader to be a comma vs slash
let mapleader=","

" syntax highlighting
syntax on

" display line numbers
set number

" using only 1 column (and 1 space) while possible
set numberwidth=1

" we are using dark background in vim
set background=dark

" ignore these files when completing
set wildignore+=.git,*.pyc

" use spaces, not tabs, for autoindent/tab key.
set expandtab

" don't wrap text
set nowrap

" don't wrap text in the middle of a word
set linebreak

" always set auto-indenting on
set autoindent

" use smart indent if there is no indent file
set smartindent

" <tab> inserts 4 spaces
set tabstop=4

" but an indent level is 4 spaces wide.
set shiftwidth=4

" <BS> over an autoindent deletes both spaces.
set softtabstop=4

" rounds indent to a multiple of shiftwidth
set shiftround

" show matching <> (html mainly) as well
set matchpairs+=<:>

" disable folding
set nofoldenable

" don't bell or blink
set noerrorbells
set vb t_vb=

" keep our cursor in the middle of the screen
set scrolloff=100
set sidescrolloff=30

" show whitespace
set list
set listchars=tab:>-,trail:~

" default to using case insensitive searches ...
set ignorecase

" ... unless uppercase letters are used in the regex.
set smartcase

" handle tabs more intelligently while searching
set smarttab

" highlight searches by default.
set hlsearch

" incrementally search while typing a /regex
set incsearch

" improve response time of plugins, etc
set updatetime=100

" add hyphens to the list of "word characters" so that they aren't word
" separators anymore
set iskeyword+=-

" remove trailing whitespace on <leader>S
noremap <leader>S :%s/\s\+$//<cr>:let @/=''<CR>

" load Vundle for plugin management
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage itself. To install new plugins, update all plugins, and
" remove extra plugins without any confirmations (such as after modifying the
" set of plugins), run:
"   vim +PluginInstall! +PluginClean! +qall
"   vim +GoInstallBinaries +qall
Plugin 'gmarik/Vundle.vim'

" Show git diffs in a gutter
Plugin 'airblade/vim-gitgutter'

" Improved status bar
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Code comments
Plugin 'tpope/vim-commentary'

" Custom color scheme
Plugin 'dolph/vim-colors-solarized-black'

" Quickly switch between open buffers
Plugin 'fholgado/minibufexpl.vim'

" Tab completion
Plugin 'ervandew/supertab'

" Run flake8 on save
Plugin 'nvie/vim-flake8'

" File browser
Plugin 'scrooloose/nerdtree'

" Rust support
Plugin 'rust-lang/rust.vim'

" Go support
Plugin 'fatih/vim-go'

" TOML support
Plugin 'cespare/vim-toml'

" Syntax highlighting for CSV files
Plugin 'mechatroner/rainbow_csv'

" Markdown support
" Plugin 'godlygeek/tabular' " must appear before plasticboy/vim-markdown
" Plugin 'plasticboy/vim-markdown'
Bundle 'gabrielelana/vim-markdown'

" Unifies vim and tmux split navigation.
Bundle 'christoomey/vim-tmux-navigator'

" Add support for PlantUML syntax
Plugin 'tyru/open-browser.vim'
Plugin 'aklt/plantuml-syntax'
Plugin 'weirongxu/plantuml-previewer.vim'

" end loading plugins
call vundle#end()
filetype plugin indent on

" set color theme
silent! colorscheme solarized

" set shortcut key and open NerdTree at start
map <leader>n :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.pyc$', '\.egg-info$', '\.db$']
" disable key mappings that conflict with vim-tmux-navigator
let g:NERDTreeMapJumpNextSibling=""
let g:NERDTreeMapJumpPrevSibling=""

" run flake8 on open & save
autocmd BufReadPost *.py call Flake8()
autocmd BufWritePost *.py call Flake8()

" run rust auto-formatting on save
" requires `cargo install rustfmt`
let g:rustfmt_autosave = 1

" enable spell checking
set spell spelllang=en_us

" disable double spacing between sentences
set nojoinspaces

" Use the X11 clipboard (shared with tmux, over SSH, etc)
" set clipboard=unnamedplus " does not seem to be needed with i3 + tmux + gvim?

" Always use unix-style line endings
set ff=unix

" 2-space indention in YAML files
autocmd FileType yaml setlocal tabstop=2 sts=2 shiftwidth=2 expandtab

" 2-space indention in HTML files
autocmd FileType html setlocal tabstop=2 sts=2 shiftwidth=2 expandtab

" 4-space tab-based in Go files
autocmd FileType go setlocal noexpandtab listchars=tab:\ \ ,trail:~
" Automatically format Go files.
" autocmd BufWritePre *.go Fmt

" Disable the creation of *.swp files (allows write conflicts)
set noswapfile

" gitgutter configuration
let g:gitgutter_enabled = 1
let g:gitgutter_grep = 'rg'
let g:gitgutter_set_sign_backgrounds = 1
highlight SignColumn ctermbg=16
highlight GitGutterAdd ctermfg=2 ctermbg=16
highlight GitGutterChange ctermfg=3 ctermbg=16
highlight GitGutterDelete ctermfg=1 ctermbg=16

" status bar configuration
let g:airline_theme='dark_minimal'
let g:airline_section_z = ''
