- name: Update the font cache
  ansible.builtin.command: fc-cache -v
  changed_when: true

- name: Restart pulseaudio
  become_user: "{{ whoami }}"
  ansible.builtin.command: pulseaudio -k
  register: task
  changed_when: true
  failed_when: task.rc != 0 and 'No such process' not in task.stderr

- name: Clear xkb cache
  ansible.builtin.shell:
    cmd: rm -rf /var/lib/xkb/*
  changed_when: true

- name: Restart i3
  become_user: "{{ whoami }}"
  ansible.builtin.shell: unset I3SOCK; i3-msg restart
  changed_when: true
