- name: restart pulseaudio
  become_user: "{{ whoami }}"
  command: pulseaudio -k
  register: task
  failed_when: task.rc != 0 and 'No such process' not in task.stderr

- name: clear xkb cache
  shell:
    cmd: rm -rf /var/lib/xkb/*
    # The file module does not have an idempotent way to delete contents of
    # directory, without touching the directory itself.
    warn: false

- name: restart i3
  become_user: "{{ whoami }}"
  command: i3-msg restart

- name: reload X database
  become_user: "{{ whoami }}"
  command: xrdb /home/{{ whoami }}/.Xresources
