- name: install git and friends
  pacman:
    name:
    - gist
    - git
    - hub
  when: ansible_distribution == 'Archlinux'

- name: install git and friends
  apt:
    name:
    - gist
    - git
    force_apt_get: true
  when: ansible_distribution == 'Ubuntu'

- name: install hub
  snap:
    name:
    - hub
    classic: true
  when: ansible_distribution == 'Ubuntu'

- name: configure hub
  template:
    src: home/config/hub
    dest: /home/dolph/.config/hub
    owner: dolph
    group: dolph

- name: configure git, gist
  template:
    src: "home/{{ item }}"
    dest: "/home/dolph/.{{ item }}"
    owner: dolph
    group: dolph
  with_items:
  - gitconfig
  - gitignore_global
  - gist
