- name: create ssh directory
  file:
    path: /home/dolph/.ssh
    state: directory
    owner: dolph
    group: dolph

- name: generate ssh identity
  openssh_keypair:
    path: /home/dolph/.ssh/id_rsa
    size: 4096
    comment: "dolph@{{ ansible_hostname }}"
    owner: dolph
    group: dolph
