- name: install tmux on arch
  pacman:
    name:
    - tmux
    - xsel
  when: ansible_distribution == 'Archlinux'

- name: install tmux on ubuntu
  apt:
    name:
    - tmux
    - xsel
    force_apt_get: true
  when: ansible_distribution == 'Ubuntu'

- name: install tmux on fedora
  yum:
    name:
    - tmux
    - xsel
  when: ansible_distribution == 'Fedora'

- name: create tmux plugins dir
  become: true
  become_user: dolph
  file:
    path: ~/.tmux-plugins
    state: directory

- name: install tmux plugins
  become: true
  become_user: dolph
  git:
    repo: "https://github.com/tmux-plugins/tmux-{{ item }}.git"
    dest: "~/.tmux-plugins/{{ item }}"
  register: git_result
  with_items:
  - yank
  - open

- name: configure tmux
  template:
    src: home/tmux.conf
    dest: /home/dolph/.tmux.conf
    owner: dolph
    group: dolph
  register: tmux_conf
  tags: configure-tmux

- name: check if tmux is running
  become: true
  become_user: dolph
  command: tmux info
  failed_when: false
  changed_when: false
  register: tmux_running

- name: apply tmux config
  become: true
  become_user: dolph
  command: tmux source-file /home/dolph/.tmux.conf
  when: tmux_conf.changed and tmux_running.rc == 0
