- name: install tmux on arch
  pacman:
    name: tmux
  when: ansible_distribution == 'Archlinux'

- name: install tmux on ubuntu
  apt:
    name: tmux
    force_apt_get: true
  when: ansible_distribution == 'Ubuntu'

- name: create tmux plugins dir
  become: true
  become_user: dolph
  file:
    path: ~/.tmux-plugins
    state: directory

- name: install tmux yank plugin
  become: true
  become_user: dolph
  git:
    repo: https://github.com/tmux-plugins/tmux-yank.git
    dest: ~/.tmux-plugins/yank
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: configure tmux
  template:
    src: home/tmux.conf
    dest: /home/dolph/.tmux.conf
    owner: dolph
    group: dolph
  register: tmux_conf

- name: check if tmux is running
  become: true
  become_user: dolph
  command: tmux info
  failed_when: false
  changed_when: false
  register: tmux_running

- name: apply tmux config
  become: true
  become_user: dolph
  command: tmux source-file /home/dolph/.tmux.conf
  when: tmux_conf.changed and tmux_running.rc == 0
