- name: install vim on arch
  pacman:
    name: vim
  when: ansible_distribution == 'Archlinux'

- name: uninstall vi
  pacman:
    name: vi
    state: absent
  when: ansible_distribution == 'Archlinux'

- name: install vim on ubuntu
  apt:
    name: vim
    force_apt_get: true
  when: ansible_distribution == 'Ubuntu'

- name: configure vim
  template:
    src: home/vimrc
    dest: /home/dolph/.vimrc
    owner: dolph
    group: dolph

- name: install vim plugin manager
  become: true
  become_user: dolph
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: install vim plugins
  become: true
  become_user: dolph
  command: vim +PluginInstall! +PluginClean! +qall
