#!/bin/sh

# Switch sh to vi mode, because the sh default is unholy.
set -o vi

# Use color by default.
export CLICOLOR=1

# Launch keychain to manage SSH passphrases.
if command -v keychain >/dev/null 2>&1 ; then
    eval `keychain --quiet --eval id_rsa`
fi

# dotfiles executables
export PATH="$PATH:$HOME/bin"

# Go
export PATH="$PATH:$HOME/go/bin"

# Rust
export RUSTPATH=$HOME/.cargo/bin
export PATH="$HOME/.cargo/bin:$PATH"
